project:
  type: book
  output-dir: _book

website:
  favicon: LOGOunach.png
  reader-mode: true
  search:
    location: sidebar
    type: overlay
  comments:
    hypothesis: true

book:
  title: "Tesis"
  reader-mode: true
  language: es
  output-file: "Tesis_MBCR"
  image: LOGOunach.png
  cover-image: LOGOunach.png
  sharing: [twitter, facebook]
  downloads: [pdf, epub]
  favicon: LOGOunach.png
  sidebar:
    logo: LOGOunach.png
    style: floating
    collapse-level: 2
    border: true
    search: true
  open-graph: true
  twitter-card: true
  repo-url: https://github.com/maribecrurod-art/CNN_HMM_tesis
  repo-actions: [edit, issue, source]
  page-navigation: true
  chapters:
    - index.qmd
    - capitulo1.qmd

comments:
  hypothesis: true

format:
  html:
    theme:
      dark: darkly
      light: cerulean
    css: styles.css
    highlight-style: a11y
    lang: es
    html-math-method: mathjax
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
    code-copy: true
    code-fold: true

  pdf:
    lang: es
    documentclass: scrreprt
    papersize: us-letter
    titlegraphic: LOGOunach.png
    institution: Benemérita Universidad Autónoma de Chiapas
    email: mariana.cruz68@unach.mx
    keep-tex: true

  epub:
    cover-image: LOGOunach.png

editor: visual